---
title: "Tarea 2 de septiembre"
format: html
editor: visual
author: Melina Varhulik
date: 2/9/2025
---

## Tarea

Escribir el codigo para cargar los datos del indec

Elegir tres variables de los datos del indec

Eventualmente hacer la transformación (traducir al español)

Visualizar la distribución

Determinar si parece normal. En caso de que no sea normal especular por qué.

```{r}
#| include: false
library(tidyverse)
```

```{r}
indec <- read_delim(
  "../data/usu_individual_T125.txt",
  delim = ";")


datos <- indec %>%
  select(CH04, CH06, ITF) %>%
  rename(
    sexo = CH04,
    edad = CH06,
    ingreso_total = ITF
  )
```

```{r}
colnames(indec) <- gsub("\"", "", colnames(indec))
```

```{r}

```

```{r}
ggplot(datos, aes(x = ingreso_total)) +
  geom_density()+scale_x_continuous(breaks =c(10^6,10^7)
  )

```

```{r}
ggplot(datos, aes(x = sexo)) +
  geom_bar()
```

```{r}
ggplot(datos, aes(x = edad)) +
  geom_density()
```

```{r}
list(datos_indec)
```

```{r}
datos|>
  ggplot(aes(ingreso_total,edad))+
  geom_point()
  
```

```{r}
datos_indec <- readr::read_delim("../data/usu_individual_T125.txt", delim = ";")

```

```{r}
source("R/poner_genero.R")
datos<- readr::read_delim("../data/usu_individual_T125.txt",delim = ";" )
datos<- datos |>
  poner_genero ()

```
