---
title: "Seminario de Ciencia de Datos"
format:
  html:
    theme: darkly
    css: styles.css
---

## Presentaciones y Notas


### Clase 1: Arranque
* [Arranque](presentaciones/1-inicio-y-setup.html)
* [presentacion](presentacion.html)
* [Tarea para el 11 de agosto 2025](tarea-2025-08-04.html)

### Clase 2: Admin y R
* [Admin y R](presentaciones/2-sincronizar-repositorios-primer-codigo-y-analysis.html)
* [Notas de la clase 12 de agosto 2025](notas-2025-08-12.html)
* [Tarea para agosto 20](tarea-para-la-agosto-20.html)

### Clase 3: Revisión de la teoría
* [Revisión de la teoría](presentaciones/3-centralizacion-y-dispersión.html)
* [notas-2025-08-20](notas-2025-08-20.html)
* [tarea-2025-08-20](tarea-2025-08-20.html)
* [Notas de la clase 2025-08-26](notas-2025-08-26.html)
* [tarea-2025-08-26](tarea-2025-08-26.html)

### Clase 5: Probabilidad y estimación de parámetros
* [Probabilidad y estimación de parámetros](presentaciones/5-probabilidad-y-estimacion-de-parametros.html)
* [Notas dela clase 2025-09-02](notas-de-la-clase-2025-09-02.html)
* [tarea-2025-09-02](tarea-2025-09-02.html)

### Clase 6: Método científico. Manipulación de datos.
* [Método científico. Manipulación de datos.](presentaciones/6-metodo-científico.html)
* [notas-de-la-clase-2025-09-09](notas-de-la-clase-2025-09-09.html)
* [tarea-2025-09-09](tarea-2025-09-09.html)

### Clase 7: Pruebas de independencia
* [Pruebas de independencia](presentaciones/7-pruebas-de-independencia.html)
* [Análisis de Prueba](notas-de-la-clase-2025-09-23.html)
